(
    ONBOARDING_NAME,
    ONBOARDING_TIMEZONE,
    ONBOARDING_TIME,
    MAIN_MENU,
    CHECK_IN_MOOD,
    CHECK_IN_TEXT,
    CHECK_IN_GUIDANCE_OFFER,
) = range(7)

LOW_MOOD_THRESHOLD = 4
CRISIS_MOOD_THRESHOLD = 2
